version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  apiforrecipes:
    image: apiforrecipes
    build:
      context: .
      dockerfile: ApiForRecipes/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=recipe_db;Username=postgres;Password=postgres


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - apiforrecipes
    environment:
      NODE_ENV: production

    stdin_open: true
    tty: true

volumes:
  postgres_data:

